---
- hosts: database
  become: true
  tasks:
    - name: install mysql-server
      yum: name=mysql-server state=present update_cache=yes

    - name: ensure mysql started
      service: name=mysqld state=started enabled=yes
